namespace Ama.CRDT.ShowCase.LargerThanMemory.Services;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Ama.CRDT.Services;
using Ama.CRDT.ShowCase.LargerThanMemory.Models;
using Microsoft.Data.Sqlite;

/// <summary>
/// Provides high-speed querying logic directly against the SQLite projection database generated by <see cref="BlogPostSqliteProjector"/>.
/// </summary>
public sealed class BlogPostReadRepository
{
    private readonly string connectionString;

    public BlogPostReadRepository(ReplicaContext replicaContext)
    {
        connectionString = $"Data Source=projections_{replicaContext.ReplicaId}.db";
    }

    public async Task<List<(Guid Id, string Title)>> GetPostsAsync()
    {
        var results = new List<(Guid, string)>();
        using var conn = new SqliteConnection(connectionString);
        await conn.OpenAsync().ConfigureAwait(false);
        using var cmd = conn.CreateCommand();
        cmd.CommandText = "SELECT Id, Title FROM BlogPosts";
        
        using var reader = await cmd.ExecuteReaderAsync().ConfigureAwait(false);
        while (await reader.ReadAsync().ConfigureAwait(false))
        {
            if (Guid.TryParse(reader.GetString(0), out var id))
            {
                results.Add((id, reader.GetString(1)));
            }
        }
        return results;
    }

    public async Task<BlogPost?> GetPostAsync(Guid id)
    {
        using var conn = new SqliteConnection(connectionString);
        await conn.OpenAsync().ConfigureAwait(false);
        using var cmd = conn.CreateCommand();
        cmd.CommandText = "SELECT Title, Content FROM BlogPosts WHERE Id = @Id";
        cmd.Parameters.AddWithValue("@Id", id.ToString());
        
        using var reader = await cmd.ExecuteReaderAsync().ConfigureAwait(false);
        if (await reader.ReadAsync().ConfigureAwait(false))
        {
            return new BlogPost 
            { 
                Id = id, 
                Title = reader.GetString(0), 
                Content = reader.GetString(1) 
            };
        }
        return null;
    }

    public async Task<long> GetTagsCountAsync(Guid id)
    {
        using var conn = new SqliteConnection(connectionString);
        await conn.OpenAsync().ConfigureAwait(false);
        using var cmd = conn.CreateCommand();
        cmd.CommandText = "SELECT COUNT(*) FROM Tags WHERE PostId = @Id";
        cmd.Parameters.AddWithValue("@Id", id.ToString());
        
        return (long)(await cmd.ExecuteScalarAsync().ConfigureAwait(false) ?? 0L);
    }

    public async Task<List<string>> GetTagsAsync(Guid id, int limit, int offset)
    {
        var results = new List<string>();
        using var conn = new SqliteConnection(connectionString);
        await conn.OpenAsync().ConfigureAwait(false);
        using var cmd = conn.CreateCommand();
        cmd.CommandText = "SELECT Tag FROM Tags WHERE PostId = @Id LIMIT @Limit OFFSET @Offset";
        cmd.Parameters.AddWithValue("@Id", id.ToString());
        cmd.Parameters.AddWithValue("@Limit", limit);
        cmd.Parameters.AddWithValue("@Offset", offset);
        
        using var reader = await cmd.ExecuteReaderAsync().ConfigureAwait(false);
        while (await reader.ReadAsync().ConfigureAwait(false))
        {
            results.Add(reader.GetString(0));
        }
        return results;
    }

    public async Task<long> GetCommentsCountAsync(Guid id)
    {
        using var conn = new SqliteConnection(connectionString);
        await conn.OpenAsync().ConfigureAwait(false);
        using var cmd = conn.CreateCommand();
        cmd.CommandText = "SELECT COUNT(*) FROM Comments WHERE PostId = @Id";
        cmd.Parameters.AddWithValue("@Id", id.ToString());
        
        return (long)(await cmd.ExecuteScalarAsync().ConfigureAwait(false) ?? 0L);
    }

    public async Task<List<Comment>> GetCommentsAsync(Guid id, int limit, int offset)
    {
        var results = new List<Comment>();
        using var conn = new SqliteConnection(connectionString);
        await conn.OpenAsync().ConfigureAwait(false);
        using var cmd = conn.CreateCommand();
        cmd.CommandText = "SELECT CreatedAt, Author, Text FROM Comments WHERE PostId = @Id ORDER BY CreatedAt DESC LIMIT @Limit OFFSET @Offset";
        cmd.Parameters.AddWithValue("@Id", id.ToString());
        cmd.Parameters.AddWithValue("@Limit", limit);
        cmd.Parameters.AddWithValue("@Offset", offset);
        
        using var reader = await cmd.ExecuteReaderAsync().ConfigureAwait(false);
        while (await reader.ReadAsync().ConfigureAwait(false))
        {
            results.Add(new Comment(
                Guid.Empty, 
                reader.GetString(1),
                reader.GetString(2),
                DateTimeOffset.Parse(reader.GetString(0))
            ));
        }
        return results;
    }
}