namespace Ama.CRDT.Services.Strategies;

using Ama.CRDT.Attributes;
using Ama.CRDT.Attributes.Strategies;
using Ama.CRDT.Models;
using Ama.CRDT.Models.Intents;
using Ama.CRDT.Models.Partitioning;
using Ama.CRDT.Services;
using Ama.CRDT.Services.Helpers;
using Ama.CRDT.Services.Partitioning;
using Ama.CRDT.Services.GarbageCollection;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using Ama.CRDT.Services.Providers;
using Ama.CRDT.Attributes.Strategies.Semantic;

/// <summary>
/// Implements a CRDT strategy for collections that are treated as sorted sets. It utilizes Last-Writer-Wins (LWW) conflict resolution logic under the hood and ensures the collection remains sorted after operations.
/// This strategy assumes elements can be uniquely identified and compared. Sorting can be configured via the <see cref="CrdtSortedSetStrategyAttribute.SortPropertyName"/>.
/// </summary>
[CrdtSupportedType(typeof(IList))]
[CrdtSupportedType(typeof(ISet<>))]
[CrdtSupportedIntent(typeof(AddIntent))]
[CrdtSupportedIntent(typeof(RemoveValueIntent))]
[Commutative]
[Associative]
[Idempotent]
[StateBased]
public sealed class SortedSetStrategy(
    IElementComparerProvider comparerProvider, 
    ICrdtTimestampProvider timestampProvider,
    ReplicaContext replicaContext) : IPartitionableCrdtStrategy
{
    private readonly string replicaId = replicaContext.ReplicaId;

    /// <summary>
    /// Defines the type of difference operation in a Longest Common Subsequence (LCS) comparison.
    /// </summary>
    public enum LcsDiffEntryType { 
        /// <summary>
        /// Indicates that an element was found in both the original and modified collections.
        /// </summary>
        Match,
        /// <summary>
        /// Indicates that an element was added to the modified collection.
        /// </summary>
        Add,
        /// <summary>
        /// Indicates that an element was removed from the original collection.
        /// </summary>
        Remove
    }

    /// <summary>
    /// Represents a single entry in the difference list generated by the LCS algorithm, detailing a match, addition, or removal.
    /// </summary>
    /// <param name="Type">The type of the difference operation (<see cref="LcsDiffEntryType.Match"/>, <see cref="LcsDiffEntryType.Add"/>, or <see cref="LcsDiffEntryType.Remove"/>).</param>
    /// <param name="OldIndex">The index of the element in the original collection. This is -1 for an <see cref="LcsDiffEntryType.Add"/> operation.</param>
    /// <param name="NewIndex">The index of the element in the modified collection. This is -1 for a <see cref="LcsDiffEntryType.Remove"/> operation.</param>
    public readonly record struct LcsDiffEntry(LcsDiffEntryType Type, int OldIndex, int NewIndex);
    
    /// <inheritdoc/>
    public void GeneratePatch(GeneratePatchContext context)
    {
        var (operations, nestedDiffs, path, property, originalValue, modifiedValue, originalRoot, modifiedRoot, originalMeta, changeTimestamp, clock) = context;

        var fromArray = (originalValue as IEnumerable)?.Cast<object>().ToList() ?? new List<object>();
        var toArray = (modifiedValue as IEnumerable)?.Cast<object>().ToList() ?? new List<object>();

        var elementType = PocoPathHelper.GetCollectionElementType(property);
        var comparer = comparerProvider.GetComparer(elementType);
        
        var diff = Diff(fromArray, toArray, comparer);

        var removeOps = new List<CrdtOperation>();
        var addOps = new List<CrdtOperation>();

        foreach (var entry in diff)
        {
            if (entry.Type == LcsDiffEntryType.Match)
            {
                var fromItem = fromArray[entry.OldIndex];
                var toItem = toArray[entry.NewIndex];
                
                if (!Equals(fromItem, toItem))
                {
                    var itemPath = $"{path}[{entry.OldIndex}]";
                    var diffContext = new DifferentiateObjectContext(itemPath, elementType, fromItem, toItem, originalRoot, modifiedRoot, originalMeta, operations, changeTimestamp);
                    nestedDiffs.Add(diffContext);
                }
            }
            else if (entry.Type == LcsDiffEntryType.Add)
            {
                var addPath = $"{path}[{entry.NewIndex}]";
                var addedItem = toArray[entry.NewIndex];
                addOps.Add(new CrdtOperation(Guid.NewGuid(), replicaId, addPath, OperationType.Upsert, addedItem, changeTimestamp, clock));
            }
            else if (entry.Type == LcsDiffEntryType.Remove)
            {
                var removePath = $"{path}[{entry.OldIndex}]";
                var removedItem = fromArray[entry.OldIndex];
                removeOps.Add(new CrdtOperation(Guid.NewGuid(), replicaId, removePath, OperationType.Remove, removedItem, changeTimestamp, clock));
            }
        }

        operations.AddRange(removeOps);
        operations.AddRange(addOps);
    }

    /// <inheritdoc/>
    public CrdtOperation GenerateOperation(GenerateOperationContext context)
    {
        var (_, _, jsonPath, _, intent, timestamp, clock) = context;

        // A dummy index like `[-1]` is used since ApplyOperation solely extracts the path up to `[` 
        // and manages elements based on the value mapping in the set.
        return intent switch
        {
            AddIntent add => new CrdtOperation(Guid.NewGuid(), replicaId, $"{jsonPath}[-1]", OperationType.Upsert, add.Value, timestamp, clock),
            RemoveValueIntent remove => new CrdtOperation(Guid.NewGuid(), replicaId, $"{jsonPath}[-1]", OperationType.Remove, remove.Value, timestamp, clock),
            _ => throw new NotSupportedException($"Intent {intent.GetType().Name} is not supported by {nameof(SortedSetStrategy)}.")
        };
    }
    
    /// <inheritdoc/>
    public CrdtOperationStatus ApplyOperation(ApplyOperationContext context)
    {
        var (root, metadata, operation) = context;

        var lastBracket = operation.JsonPath.LastIndexOf('[');
        if (lastBracket <= 0 || !operation.JsonPath.EndsWith("]"))
        {
            return CrdtOperationStatus.PathResolutionFailed;
        }

        var collectionPath = operation.JsonPath[..lastBracket];
        var (parent, property, _) = PocoPathHelper.ResolvePath(root, collectionPath);

        if (parent is null || property is null)
        {
            return CrdtOperationStatus.PathResolutionFailed;
        }

        var rawCollection = PocoPathHelper.GetAccessor(property).Getter(parent);
        if (rawCollection is not IEnumerable collection)
        {
            return CrdtOperationStatus.PathResolutionFailed;
        }

        var elementType = PocoPathHelper.GetCollectionElementType(property);
        var comparer = comparerProvider.GetComparer(elementType);
        var listRepresentation = collection.Cast<object>().ToList();

        if (!metadata.SortedSets.TryGetValue(collectionPath, out var state))
        {
            var adds = new Dictionary<object, ICrdtTimestamp>(comparer);
            foreach (var item in listRepresentation)
            {
                adds[item] = timestampProvider.Create(0);
            }
            state = new LwwSetState(adds, new Dictionary<object, CausalTimestamp>(comparer));
            metadata.SortedSets[collectionPath] = state;
        }

        var itemValue = PocoPathHelper.ConvertValue(operation.Value, elementType);
        if (itemValue is null) return CrdtOperationStatus.StrategyApplicationFailed;

        switch (operation.Type)
        {
            case OperationType.Upsert:
                if (!state.Adds.TryGetValue(itemValue, out var addTimestamp) || operation.Timestamp.CompareTo(addTimestamp) > 0)
                {
                    state.Adds[itemValue] = operation.Timestamp;
                }
                break;
            case OperationType.Remove:
                if (!state.Removes.TryGetValue(itemValue, out var removeCausalTs) || operation.Timestamp.CompareTo(removeCausalTs.Timestamp) > 0)
                {
                    state.Removes[itemValue] = new CausalTimestamp(operation.Timestamp, operation.ReplicaId, operation.Clock);
                }
                break;
            default:
                return CrdtOperationStatus.StrategyApplicationFailed;
        }

        bool isLiveNow = false;
        if (state.Adds.TryGetValue(itemValue, out var finalAddTs))
        {
            if (!state.Removes.TryGetValue(itemValue, out var finalRemoveCausalTs) || finalAddTs.CompareTo(finalRemoveCausalTs.Timestamp) > 0)
            {
                isLiveNow = true;
            }
        }

        var list = rawCollection as IList;

        if (isLiveNow)
        {
            if (list != null)
            {
                var existingIndex = -1;
                for (var i = 0; i < list.Count; i++)
                {
                    if (comparer.Equals(list[i], itemValue))
                    {
                        existingIndex = i;
                        break;
                    }
                }

                if (existingIndex != -1)
                {
                    list[existingIndex] = itemValue;
                }
                else
                {
                    list.Add(itemValue);
                }
            }
            else
            {
                var existing = collection.Cast<object>().FirstOrDefault(x => comparer.Equals(x, itemValue));
                if (existing != null) PocoPathHelper.RemoveFromCollection(rawCollection, existing);
                PocoPathHelper.AddToCollection(rawCollection, itemValue);
            }

            SortCollection(rawCollection, property);
        }
        else
        {
            if (list != null)
            {
                var indexToRemove = -1;
                for (var i = 0; i < list.Count; i++)
                {
                    if (comparer.Equals(list[i], itemValue))
                    {
                        indexToRemove = i;
                        break;
                    }
                }

                if (indexToRemove != -1)
                {
                    list.RemoveAt(indexToRemove);
                }
            }
            else
            {
                var existing = collection.Cast<object>().FirstOrDefault(x => comparer.Equals(x, itemValue));
                if (existing != null) PocoPathHelper.RemoveFromCollection(rawCollection, existing);
            }
        }

        return CrdtOperationStatus.Success;
    }

    /// <inheritdoc/>
    public void Compact(CompactionContext context)
    {
        if (!context.Metadata.SortedSets.TryGetValue(context.PropertyPath, out var state)) return;

        var deadItemsToRemove = new List<object>();

        foreach (var kvp in state.Removes)
        {
            var item = kvp.Key;
            var removeCausal = kvp.Value;
            var removeTs = removeCausal.Timestamp;

            if (state.Adds.TryGetValue(item, out var addTs))
            {
                // In LWW, highest timestamp wins. If addTs <= removeTs, Remove is newer/equal.
                if (addTs.CompareTo(removeTs) <= 0)
                {
                    if (context.Policy.IsSafeToCompact(new CompactionCandidate(Timestamp: removeTs, ReplicaId: removeCausal.ReplicaId, Version: removeCausal.Clock)) && 
                        context.Policy.IsSafeToCompact(new CompactionCandidate(Timestamp: addTs)))
                    {
                        deadItemsToRemove.Add(item);
                    }
                }
            }
            else
            {
                if (context.Policy.IsSafeToCompact(new CompactionCandidate(Timestamp: removeTs, ReplicaId: removeCausal.ReplicaId, Version: removeCausal.Clock)))
                {
                    deadItemsToRemove.Add(item);
                }
            }
        }

        foreach (var item in deadItemsToRemove)
        {
            state.Removes.Remove(item);
            state.Adds.Remove(item);
        }
    }

    /// <inheritdoc/>
    public IComparable? GetStartKey(object data, PropertyInfo partitionableProperty)
    {
        var collection = PocoPathHelper.GetAccessor(partitionableProperty).Getter(data) as IEnumerable;
        if (collection == null) return null;

        var attr = partitionableProperty.GetCustomAttribute<CrdtSortedSetStrategyAttribute>();
        var sortPropName = attr?.SortPropertyName;

        var keys = new List<IComparable>();
        foreach (var item in collection)
        {
            var key = GetSortKey(item, sortPropName);
            if (key is IComparable c) keys.Add(c);
            else if (key != null) keys.Add(key.ToString()!);
        }

        if (keys.Count == 0) return null;
        return keys.OrderBy(k => k).FirstOrDefault();
    }

    /// <inheritdoc/>
    public IComparable? GetKeyFromOperation(CrdtOperation operation, string partitionablePropertyPath)
    {
        if (!operation.JsonPath.StartsWith(partitionablePropertyPath, StringComparison.Ordinal)) return null;

        // Note: For elements, GetSortKey will inherently try to parse "Id" or use the element itself.
        var sortKey = GetSortKey(operation.Value, null);
        return sortKey as IComparable ?? sortKey?.ToString() as IComparable;
    }

    /// <inheritdoc/>
    public IComparable GetMinimumKey(PropertyInfo partitionableProperty)
    {
        var elementType = PocoPathHelper.GetCollectionElementType(partitionableProperty);
        var attr = partitionableProperty.GetCustomAttribute<CrdtSortedSetStrategyAttribute>();
        var sortPropName = attr?.SortPropertyName ?? "Id";
        
        var prop = elementType.GetProperty(sortPropName, BindingFlags.Public | BindingFlags.Instance | BindingFlags.IgnoreCase);
        if (prop != null)
        {
            return GetMinimumKeyForType(prop.PropertyType);
        }

        return string.Empty;
    }

    /// <inheritdoc/>
    public SplitResult Split(object originalData, CrdtMetadata originalMetadata, PropertyInfo partitionableProperty)
    {
        var documentType = partitionableProperty.DeclaringType!;
        var path = $"$.{char.ToLowerInvariant(partitionableProperty.Name[0])}{partitionableProperty.Name[1..]}";

        var collection = PocoPathHelper.GetAccessor(partitionableProperty).Getter(originalData) as IEnumerable;
        var list = collection?.Cast<object>().ToList() ?? new List<object>();

        if (!originalMetadata.SortedSets.TryGetValue(path, out var state))
        {
            var elementType = PocoPathHelper.GetCollectionElementType(partitionableProperty);
            var comparer = comparerProvider.GetComparer(elementType);
            var adds = new Dictionary<object, ICrdtTimestamp>(comparer);
            foreach (var item in list) adds[item] = timestampProvider.Create(0);
            state = new LwwSetState(adds, new Dictionary<object, CausalTimestamp>(comparer));
            originalMetadata.SortedSets[path] = state;
        }

        if (state.Adds.Count + state.Removes.Count < 2)
        {
            throw new InvalidOperationException("Cannot split a partition with less than 2 items.");
        }

        var elementTypeProp = PocoPathHelper.GetCollectionElementType(partitionableProperty);
        var comparerProp = comparerProvider.GetComparer(elementTypeProp);
        var attr = partitionableProperty.GetCustomAttribute<CrdtSortedSetStrategyAttribute>();
        var sortPropName = attr?.SortPropertyName;

        var allItems = state.Adds.Keys.Concat(state.Removes.Keys).Distinct(comparerProp);
        var itemsWithKeys = allItems.Select(x => new { Item = x, SortKey = GetSortKey(x, sortPropName) as IComparable ?? GetSortKey(x, sortPropName)?.ToString() as IComparable })
            .Where(x => x.SortKey != null).OrderBy(x => x.SortKey).ToList();

        if (itemsWithKeys.Count < 2)
        {
            throw new InvalidOperationException("Cannot split a partition with less than 2 items.");
        }

        var splitIndex = itemsWithKeys.Count / 2;
        var splitKey = itemsWithKeys[splitIndex].SortKey;

        var keys1 = itemsWithKeys.Take(splitIndex).Select(x => x.SortKey).ToHashSet();
        
        var adds1 = new Dictionary<object, ICrdtTimestamp>(comparerProp);
        var adds2 = new Dictionary<object, ICrdtTimestamp>(comparerProp);
        foreach (var kvp in state.Adds)
        {
            var k = GetSortKey(kvp.Key, sortPropName) as IComparable ?? GetSortKey(kvp.Key, sortPropName)?.ToString() as IComparable;
            if (keys1.Contains(k)) adds1[kvp.Key] = kvp.Value;
            else adds2[kvp.Key] = kvp.Value;
        }

        var rems1 = new Dictionary<object, CausalTimestamp>(comparerProp);
        var rems2 = new Dictionary<object, CausalTimestamp>(comparerProp);
        foreach (var kvp in state.Removes)
        {
            var k = GetSortKey(kvp.Key, sortPropName) as IComparable ?? GetSortKey(kvp.Key, sortPropName)?.ToString() as IComparable;
            if (keys1.Contains(k)) rems1[kvp.Key] = kvp.Value;
            else rems2[kvp.Key] = kvp.Value;
        }

        var meta1 = originalMetadata.DeepClone();
        var meta2 = originalMetadata.DeepClone();

        meta1.SortedSets[path] = new LwwSetState(adds1, rems1);
        meta2.SortedSets[path] = new LwwSetState(adds2, rems2);

        var doc1 = Activator.CreateInstance(documentType)!;
        var doc2 = Activator.CreateInstance(documentType)!;

        ReconstructListForSplitMerge(doc1, path, meta1.SortedSets[path], elementTypeProp, partitionableProperty.PropertyType);
        ReconstructListForSplitMerge(doc2, path, meta2.SortedSets[path], elementTypeProp, partitionableProperty.PropertyType);

        return new SplitResult(new PartitionContent(doc1, meta1), new PartitionContent(doc2, meta2), splitKey!);
    }

    /// <inheritdoc/>
    public PartitionContent Merge(object data1, CrdtMetadata meta1, object data2, CrdtMetadata meta2, PropertyInfo partitionableProperty)
    {
        var documentType = partitionableProperty.DeclaringType!;
        var path = $"$.{char.ToLowerInvariant(partitionableProperty.Name[0])}{partitionableProperty.Name[1..]}";

        var mergedDoc = Activator.CreateInstance(documentType)!;
        var mergedMeta = CrdtMetadata.Merge(meta1, meta2);

        var elementType = PocoPathHelper.GetCollectionElementType(partitionableProperty);
        var comparer = comparerProvider.GetComparer(elementType);

        var adds = new Dictionary<object, ICrdtTimestamp>(comparer);
        var rems = new Dictionary<object, CausalTimestamp>(comparer);

        if (meta1.SortedSets.TryGetValue(path, out var state1))
        {
            foreach (var kvp in state1.Adds) adds[kvp.Key] = kvp.Value;
            foreach (var kvp in state1.Removes) rems[kvp.Key] = kvp.Value;
        }
        if (meta2.SortedSets.TryGetValue(path, out var state2))
        {
            foreach (var kvp in state2.Adds)
            {
                if (!adds.TryGetValue(kvp.Key, out var existing) || kvp.Value.CompareTo(existing) > 0)
                    adds[kvp.Key] = kvp.Value;
            }
            foreach (var kvp in state2.Removes)
            {
                if (!rems.TryGetValue(kvp.Key, out var existing) || kvp.Value.Timestamp.CompareTo(existing.Timestamp) > 0)
                    rems[kvp.Key] = kvp.Value;
            }
        }

        var mergedState = new LwwSetState(adds, rems);
        mergedMeta.SortedSets[path] = mergedState;

        ReconstructListForSplitMerge(mergedDoc, path, mergedState, elementType, partitionableProperty.PropertyType);

        return new PartitionContent(mergedDoc, mergedMeta);
    }
    
    internal List<LcsDiffEntry> Diff(List<object> from, List<object> to, IEqualityComparer<object> itemComparer)
    {
        var n = from.Count;
        var m = to.Count;
        var dp = new int[n + 1, m + 1];

        for (var i = 1; i <= n; i++)
        {
            for (var j = 1; j <= m; j++)
            {
                if (itemComparer.Equals(from[i-1], to[j-1]))
                {
                    dp[i, j] = dp[i - 1, j - 1] + 1;
                }
                else
                {
                    dp[i, j] = Math.Max(dp[i - 1, j], dp[i, j - 1]);
                }
            }
        }

        var diff = new List<LcsDiffEntry>();
        var i_ptr = n;
        var j_ptr = m;
        while (i_ptr > 0 || j_ptr > 0)
        {
            if (i_ptr > 0 && j_ptr > 0 && itemComparer.Equals(from[i_ptr - 1], to[j_ptr - 1]))
            {
                diff.Add(new LcsDiffEntry(LcsDiffEntryType.Match, i_ptr - 1, j_ptr - 1));
                i_ptr--;
                j_ptr--;
            }
            else if (j_ptr > 0 && (i_ptr == 0 || dp[i_ptr, j_ptr - 1] >= dp[i_ptr - 1, j_ptr]))
            {
                diff.Add(new LcsDiffEntry(LcsDiffEntryType.Add, -1, j_ptr - 1));
                j_ptr--;
            }
            else if (i_ptr > 0 && (j_ptr == 0 || dp[i_ptr, j_ptr - 1] < dp[i_ptr - 1, j_ptr]))
            {
                diff.Add(new LcsDiffEntry(LcsDiffEntryType.Remove, i_ptr - 1, -1));
                i_ptr--;
            }
        }

        diff.Reverse();
        return diff;
    }
    
    private static void SortCollection(object collection, PropertyInfo property)
    {
        var attr = property.GetCustomAttribute<CrdtSortedSetStrategyAttribute>();
        var sortPropertyName = attr?.SortPropertyName;

        var items = ((IEnumerable)collection).Cast<object>().ToList();

        items.Sort((x, y) =>
        {
            var keyX = GetSortKey(x, sortPropertyName);
            var keyY = GetSortKey(y, sortPropertyName);
            
            int cmp;
            if (keyX is null && keyY is null) cmp = 0;
            else if (keyX is null) cmp = -1;
            else if (keyY is null) cmp = 1;
            else if (keyX is string strX && keyY is string strY)
            {
                cmp = string.Compare(strX, strY, StringComparison.Ordinal);
            }
            else if (keyX is IComparable comparableX)
            {
                cmp = comparableX.CompareTo(keyY);
            }
            else
            {
                cmp = string.Compare(keyX.ToString(), keyY.ToString(), StringComparison.Ordinal);
            }

            if (cmp == 0 && !ReferenceEquals(x, y))
            {
                if (x is string sX && y is string sY)
                {
                    return string.Compare(sX, sY, StringComparison.Ordinal);
                }
                return string.Compare(x?.ToString(), y?.ToString(), StringComparison.Ordinal);
            }

            return cmp;
        });
        
        PocoPathHelper.ClearCollection(collection);
        foreach (var item in items)
        {
            PocoPathHelper.AddToCollection(collection, item);
        }
    }

    private static void ReconstructListForSplitMerge(object root, string path, LwwSetState state, Type elementType, Type propertyType)
    {
        var (parent, property, _) = PocoPathHelper.ResolvePath(root, path);
        if (parent is null || property is null) return;

        var collection = PocoPathHelper.GetAccessor(property).Getter(parent);
        if (collection is null)
        {
            collection = PocoPathHelper.InstantiateCollection(propertyType);
            PocoPathHelper.GetAccessor(property).Setter(parent, collection);
        }

        PocoPathHelper.ClearCollection(collection);
        
        var liveItems = new List<object>();

        foreach (var kvp in state.Adds)
        {
            var item = kvp.Key;
            var addTs = kvp.Value;
            if (!state.Removes.TryGetValue(item, out var rmCausal) || addTs.CompareTo(rmCausal.Timestamp) > 0)
            {
                var converted = PocoPathHelper.ConvertValue(item, elementType);
                if (converted != null) liveItems.Add(converted);
            }
        }

        foreach (var item in liveItems)
        {
            PocoPathHelper.AddToCollection(collection, item);
        }

        SortCollection(collection, property);
    }

    private static object? GetSortKey(object? obj, string? sortPropertyName)
    {
        if (obj is null)
        {
            return null;
        }

        var type = obj.GetType();
        PropertyInfo? prop = null;

        if (!string.IsNullOrEmpty(sortPropertyName))
        {
            prop = type.GetProperty(sortPropertyName, BindingFlags.Public | BindingFlags.Instance | BindingFlags.IgnoreCase);
        }
        else
        {
            prop = type.GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.IgnoreCase);
        }
        
        if (prop is not null)
        {
            return PocoPathHelper.GetAccessor(prop).Getter(obj);
        }

        if (obj is IComparable)
        {
            return obj;
        }

        if (type.IsClass && type != typeof(string))
        {
            var properties = type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
                .Where(p => p.CanRead)
                .OrderBy(p => p.Name);
            
            var keyBuilder = new StringBuilder();
            foreach (var p in properties)
            {
                keyBuilder.Append(PocoPathHelper.GetAccessor(p).Getter(obj)?.ToString() ?? "null");
                keyBuilder.Append('|');
            }
            return keyBuilder.ToString();
        }

        return obj;
    }

    private static IComparable GetMinimumKeyForType(Type keyType)
    {
        if (keyType == typeof(string)) return string.Empty;
        if (keyType == typeof(int)) return int.MinValue;
        if (keyType == typeof(long)) return long.MinValue;
        if (keyType == typeof(short)) return short.MinValue;
        if (keyType == typeof(byte)) return byte.MinValue;
        if (keyType == typeof(Guid)) return Guid.Empty;
        if (keyType == typeof(DateTime)) return DateTime.MinValue;
        if (keyType == typeof(DateTimeOffset)) return DateTimeOffset.MinValue;
        if (keyType == typeof(char)) return char.MinValue;
        if (keyType == typeof(double)) return double.MinValue;
        if (keyType == typeof(float)) return float.MinValue;
        if (keyType == typeof(decimal)) return decimal.MinValue;

        if (keyType.IsValueType)
        {
            return (IComparable)Activator.CreateInstance(keyType)!;
        }

        throw new InvalidOperationException($"Cannot determine minimum key for type {keyType}.");
    }
}