namespace Ama.CRDT.UnitTests.Models.Serialization;

using System.Text.Json.Serialization;
using Ama.CRDT.Models;
using Ama.CRDT.UnitTests.Services.Strategies.Serialization;

/// <summary>
/// A dedicated JsonSerializerContext for the unit tests to provide AOT-compatible 
/// serialization metadata for test-specific models and generic permutations.
/// </summary>
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false)]
[JsonSerializable(typeof(CoreSerializationTestModel))]
[JsonSerializable(typeof(CrdtDocument<CoreSerializationTestModel>))]
[JsonSerializable(typeof(ApplyPatchResult<CoreSerializationTestModel>))]
[JsonSerializable(typeof(DocumentSerializationTestModel))]
[JsonSerializable(typeof(CrdtDocument<DocumentSerializationTestModel>))]
[JsonSerializable(typeof(CustomTimestamp))]
[JsonSerializable(typeof(AnotherCustomTimestamp))]
[JsonSerializable(typeof(InvalidTimestamp))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.LwwModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.LwwModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.FwwModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.FwwModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.CounterModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.CounterModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.GCounterModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.GCounterModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.BoundedCounterModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.BoundedCounterModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.MaxWinsModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.MaxWinsModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.MinWinsModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.MinWinsModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.AverageRegisterModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.AverageRegisterModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.ArrayLcsModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.ArrayLcsModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.FixedSizeArrayModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.FixedSizeArrayModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.GSetModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.GSetModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.TwoPhaseSetModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.TwoPhaseSetModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.LwwSetModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.LwwSetModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.FwwSetModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.FwwSetModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.OrSetModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.OrSetModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.LseqModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.LseqModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.RgaModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.RgaModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.SortedSetModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.SortedSetModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.LwwMapModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.LwwMapModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.FwwMapModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.FwwMapModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.OrMapModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.OrMapModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.CounterMapModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.CounterMapModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.MaxWinsMapModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.MaxWinsMapModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.MinWinsMapModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.MinWinsMapModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.VoteCounterModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.VoteCounterModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.PriorityQueueModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.PriorityQueueModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.StateMachineModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.StateMachineModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.GraphModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.GraphModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.TwoPhaseGraphModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.TwoPhaseGraphModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.ReplicatedTreeModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.ReplicatedTreeModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.EpochBoundModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.EpochBoundModel>))]
[JsonSerializable(typeof(StrategyPayloadSerializationTests.ApprovalQuorumModel))]
[JsonSerializable(typeof(CrdtDocument<StrategyPayloadSerializationTests.ApprovalQuorumModel>))]
internal partial class TestJsonSerializerContext : JsonSerializerContext
{
}