namespace Ama.CRDT.Services;

using Ama.CRDT.Models;
using Ama.CRDT.Services.Providers;
using System.Diagnostics.CodeAnalysis;

/// <summary>
/// Defines a service for managing CRDT metadata. Its responsibilities include initializing, resetting,
/// and compacting metadata state such as LWW timestamps, positional trackers, and version vectors.
/// This service is critical for enabling conflict-free merges by externalizing the state needed for resolution.
/// </summary>
public interface ICrdtMetadataManager
{
    /// <summary>
    /// Creates and initializes a new <see cref="CrdtMetadata"/> object for a given document.
    /// This method recursively traverses the document, populating LWW timestamps and initializing trackers for various strategies.
    /// It uses a timestamp generated by the configured <see cref="ICrdtTimestampProvider"/>.
    /// This is a foundational step that establishes the initial state baseline for future patch generation and application.
    /// </summary>
    /// <typeparam name="T">The type of the document.</typeparam>
    /// <param name="document">The document object to initialize metadata for.</param>
    /// <returns>A new, initialized <see cref="CrdtMetadata"/> object.</returns>
    /// <exception cref="System.ArgumentNullException">Thrown if <paramref name="document"/> is null.</exception>
    /// <example>
    /// <code>
    /// <![CDATA[
    /// var user = new User { Name = "Alice", Age = 30 };
    /// // metadataManager is an injected instance of ICrdtMetadataManager
    /// var metadata = metadataManager.Initialize(user);
    /// // Now 'metadata' contains LWW timestamps for 'Name' and 'Age' properties.
    /// ]]>
    /// </code>
    /// </example>
    CrdtMetadata Initialize<T>([DisallowNull] T document) where T : class;

    /// <summary>
    /// Creates and initializes a new <see cref="CrdtMetadata"/> object for a given document with a specific timestamp.
    /// This overload is useful for creating a consistent state snapshot at a known point in time.
    /// </summary>
    /// <typeparam name="T">The type of the document.</typeparam>
    /// <param name="document">The document object to initialize metadata for.</param>
    /// <param name="timestamp">The timestamp to use for initialization.</param>
    /// <returns>A new, initialized <see cref="CrdtMetadata"/> object.</returns>
    /// <exception cref="System.ArgumentNullException">Thrown if <paramref name="document"/> or <paramref name="timestamp"/> is null.</exception>
    /// <example>
    /// <code>
    /// <![CDATA[
    /// var user = new User { Name = "Alice", Age = 30 };
    /// var ts = new EpochTimestamp(DateTimeOffset.UtcNow.ToUnixTimeMilliseconds());
    /// var metadata = metadataManager.Initialize(user, ts);
    /// ]]>
    /// </code>
    /// </example>
    CrdtMetadata Initialize<T>([DisallowNull] T document, [DisallowNull] ICrdtTimestamp timestamp) where T : class;

    /// <summary>
    /// Populates an existing <see cref="CrdtMetadata"/> object with state derived from a document.
    /// It uses a timestamp generated by the configured <see cref="ICrdtTimestampProvider"/>.
    /// This method is essential for all strategies that derive state from the document, including LWW, sequence, and set-based strategies.
    /// </summary>
    /// <typeparam name="T">The type of the document.</typeparam>
    /// <param name="document">The CRDT document containing the data to derive metadata from and the metadata object to populate.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if <paramref name="document"/>, <paramref name="document"/>.Metadata or <paramref name="document"/>.Data is null.</exception>
    /// <example>
    /// <code>
    /// <![CDATA[
    /// var myDoc = new CrdtDocument<User>(new User { Name = "Bob" }, new CrdtMetadata());
    /// metadataManager.Initialize(myDoc); // Populates myDoc.Metadata
    /// ]]>
    /// </code>
    /// </example>
    void Initialize<T>([DisallowNull] CrdtDocument<T> document) where T : class;

    /// <summary>
    /// Populates an existing <see cref="CrdtMetadata"/> object with state derived from a document using a specific timestamp.
    /// This method is essential for all strategies that derive state from the document, including LWW, sequence, and set-based strategies.
    /// </summary>
    /// <typeparam name="T">The type of the document.</typeparam>
    /// <param name="document">The CRDT document containing the data to derive metadata from and the metadata object to populate.</param>
    /// <param name="timestamp">The timestamp to use for initialization.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if <paramref name="document"/>, <paramref name="document"/>.Metadata, <paramref name="document"/>.Data, or <paramref name="timestamp"/> is null.</exception>
    /// <example>
    /// <code>
    /// <![CDATA[
    /// var myDoc = new CrdtDocument<User>(new User { Name = "Bob" }, new CrdtMetadata());
    /// var ts = new EpochTimestamp(DateTimeOffset.UtcNow.ToUnixTimeMilliseconds());
    /// metadataManager.Initialize(myDoc, ts);
    /// ]]>
    /// </code>
    /// </example>
    void Initialize<T>([DisallowNull] CrdtDocument<T> document, [DisallowNull] ICrdtTimestamp timestamp) where T : class;

    /// <summary>
    /// Resets an existing <see cref="CrdtMetadata"/> object and re-initializes it from a document's current state.
    /// It uses a timestamp generated by the configured <see cref="ICrdtTimestampProvider"/>.
    /// This is useful when a full resynchronization of metadata is required, for instance, after loading a document from a snapshot or after a major structural change.
    /// </summary>
    /// <typeparam name="T">The type of the document.</typeparam>
    /// <param name="document">The CRDT document containing the data to derive metadata from and the metadata object to reset.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if <paramref name="document"/>, <paramref name="document"/>.Metadata or <paramref name="document"/>.Data is null.</exception>
    /// <example>
    /// <code>
    /// <![CDATA[
    /// var snapshotDoc = GetDocumentFromStorage();
    /// metadataManager.Reset(snapshotDoc); // Clears and rebuilds snapshotDoc.Metadata from scratch
    /// ]]>
    /// </code>
    /// </example>
    void Reset<T>([DisallowNull] CrdtDocument<T> document) where T : class;

    /// <summary>
    /// Resets an existing <see cref="CrdtMetadata"/> object and re-initializes it from a document using a specific timestamp.
    /// This is useful when a full resynchronization of metadata is required at a known point in time.
    /// </summary>
    /// <typeparam name="T">The type of the document.</typeparam>
    /// <param name="document">The CRDT document containing the data to derive metadata from and the metadata object to reset.</param>
    /// <param name="timestamp">The timestamp to use for initialization.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if <paramref name="document"/>, <paramref name="document"/>.Metadata, <paramref name="document"/>.Data, or <paramref name="timestamp"/> is null.</exception>
    /// <example>
    /// <code>
    /// <![CDATA[
    /// var snapshotDoc = GetDocumentFromStorage();
    /// var ts = new EpochTimestamp(DateTimeOffset.UtcNow.ToUnixTimeMilliseconds());
    /// metadataManager.Reset(snapshotDoc, ts);
    /// ]]>
    /// </code>
    /// </example>
    void Reset<T>([DisallowNull] CrdtDocument<T> document, [DisallowNull] ICrdtTimestamp timestamp) where T : class;

    /// <summary>
    /// Removes LWW tombstones from the metadata that are older than the specified threshold.
    /// This helps in managing metadata growth by garbage-collecting outdated entries. It is primarily beneficial for strategies that rely on LWW logic, such as `LwwStrategy` and `FixedSizeArrayStrategy`.
    /// </summary>
    /// <param name="metadata">The metadata object to prune.</param>
    /// <param name="threshold">The timestamp threshold. Any LWW entry older than this will be removed.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if <paramref name="metadata"/> or <paramref name="threshold"/> is null.</exception>
    /// <example>
    /// <code>
    /// <![CDATA[
    /// var threshold = new EpochTimestamp(DateTimeOffset.UtcNow.AddDays(-7).ToUnixTimeMilliseconds());
    /// metadataManager.PruneLwwTombstones(metadata, threshold);
    /// ]]>
    /// </code>
    /// </example>
    void PruneLwwTombstones([DisallowNull] CrdtMetadata metadata, [DisallowNull] ICrdtTimestamp threshold);

    /// <summary>
    /// Removes LWW-Set and Priority Queue tombstones from the metadata that are older than the specified threshold.
    /// An element is permanently removed (pruned from both adds and removes) if its remove timestamp is older than the threshold and it definitively wins over the add timestamp.
    /// </summary>
    /// <param name="metadata">The metadata object to prune.</param>
    /// <param name="threshold">The timestamp threshold. Any resolved LWW-Set tombstone older than this will be removed.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if <paramref name="metadata"/> or <paramref name="threshold"/> is null.</exception>
    /// <example>
    /// <code>
    /// <![CDATA[
    /// var threshold = new EpochTimestamp(DateTimeOffset.UtcNow.AddDays(-30).ToUnixTimeMilliseconds());
    /// metadataManager.PruneLwwSetTombstones(metadata, threshold);
    /// ]]>
    /// </code>
    /// </example>
    void PruneLwwSetTombstones([DisallowNull] CrdtMetadata metadata, [DisallowNull] ICrdtTimestamp threshold);

    /// <summary>
    /// Prunes resolved Observed-Remove (OR) Set, Map, and Replicated Tree tombstones.
    /// An element is fully pruned if its recorded 'Removes' tags completely cover its 'Adds' tags. 
    /// This safely garbage collects data for elements that are fully deleted without needing a time threshold.
    /// </summary>
    /// <param name="metadata">The metadata object to prune.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if <paramref name="metadata"/> is null.</exception>
    /// <example>
    /// <code>
    /// <![CDATA[
    /// // Automatically cleans up OR-Set elements that have been fully removed.
    /// metadataManager.PruneOrSetTombstones(metadata);
    /// ]]>
    /// </code>
    /// </example>
    void PruneOrSetTombstones([DisallowNull] CrdtMetadata metadata);

    /// <summary>
    /// Removes out-of-order seen operations from the metadata that are older than the specified threshold.
    /// This prevents unbounded growth of the exceptions set if a replica permanently drops out.
    /// </summary>
    /// <param name="metadata">The metadata object to prune.</param>
    /// <param name="threshold">The timestamp threshold. Any exception older than this will be removed.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if <paramref name="metadata"/> or <paramref name="threshold"/> is null.</exception>
    /// <example>
    /// <code>
    /// <![CDATA[
    /// var threshold = new EpochTimestamp(DateTimeOffset.UtcNow.AddHours(-1).ToUnixTimeMilliseconds());
    /// metadataManager.PruneSeenExceptions(metadata, threshold);
    /// ]]>
    /// </code>
    /// </example>
    void PruneSeenExceptions([DisallowNull] CrdtMetadata metadata, [DisallowNull] ICrdtTimestamp threshold);
    
    /// <summary>
    /// Advances the version vector for the replica that generated the operation, pruning any covered exceptions.
    /// This is a core causality tracking mechanism used by the applicator to prevent duplicate operation application.
    /// By tracking the latest contiguous causal sequence clock for each replica, it ensures that an operation is applied only once.
    /// It is automatically called for the strategies that support it after it applies the operation.
    /// </summary>
    /// <param name="metadata">The metadata object to update.</param>
    /// <param name="operation">The operation whose replica and clock sequence will be used to advance the vector.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if <paramref name="metadata"/> is null.</exception>
    /// <example>
    /// <code>
    /// <![CDATA[
    /// var ts = new EpochTimestamp(DateTimeOffset.UtcNow.ToUnixTimeMilliseconds());
    /// var operation = new CrdtOperation(OperationType.Upsert, "$.name", "Alice", ts, "replica-A", 5);
    /// metadataManager.AdvanceVersionVector(metadata, operation);
    /// // metadata.VersionVector["replica-A"] is now updated to 5 (or higher if exceptions are pruned)
    /// ]]>
    /// </code>
    /// </example>
    void AdvanceVersionVector([DisallowNull] CrdtMetadata metadata, CrdtOperation operation);

    /// <summary>
    /// Advances the version vector for a specific replica with a given causal clock sequence, pruning any covered exceptions.
    /// This is a core causality tracking mechanism used by the applicator to prevent duplicate operation application.
    /// It is automatically called for the strategies that support it after it applies the operation.
    /// </summary>
    /// <param name="metadata">The metadata object to update.</param>
    /// <param name="replicaId">The ID of the replica whose version vector is being advanced.</param>
    /// <param name="clock">The new causal clock sequence for the replica's version vector.</param>
    /// <exception cref="System.ArgumentNullException">Thrown if <paramref name="metadata"/> is null.</exception>
    /// <exception cref="System.ArgumentException">Thrown if <paramref name="replicaId"/> is null or whitespace.</exception>
    /// <example>
    /// <code>
    /// <![CDATA[
    /// metadataManager.AdvanceVersionVector(metadata, "replica-A", 6);
    /// ]]>
    /// </code>
    /// </example>
    void AdvanceVersionVector([DisallowNull] CrdtMetadata metadata, [DisallowNull] string replicaId, long clock);
}