namespace Ama.CRDT.Models.Aot;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using Ama.CRDT.Attributes;
using Ama.CRDT.Models;
using Ama.CRDT.Models.Decorators;
using Ama.CRDT.Models.Intents;
using Ama.CRDT.Models.Intents.Decorators;
using Ama.CRDT.Models.Partitioning;

/// <summary>
/// An internal AOT-generated context containing metadata for all core CRDT models.
/// This is automatically registered into the DI container by <see cref="Extensions.ServiceCollectionExtensions.AddCrdt"/>.
/// </summary>
[CrdtSerializable(typeof(AverageRegisterValue))]
[CrdtSerializable(typeof(BidirectionalSyncRequirements))]
[CrdtSerializable(typeof(CausalTimestamp))]
[CrdtSerializable(typeof(CrdtGraph))]
[CrdtSerializable(typeof(CrdtMetadata))]
[CrdtSerializable(typeof(CrdtOperation))]
[CrdtSerializable(typeof(CrdtPatch))]
[CrdtSerializable(typeof(CrdtTree))]
[CrdtSerializable(typeof(DottedVersionVector))]
[CrdtSerializable(typeof(Edge))]
[CrdtSerializable(typeof(EpochTimestamp))]
[CrdtSerializable(typeof(GraphEdgePayload))]
[CrdtSerializable(typeof(GraphVertexPayload))]
[CrdtSerializable(typeof(JournaledOperation))]
[CrdtSerializable(typeof(LseqIdentifier))]
[CrdtSerializable(typeof(LseqItem))]
[CrdtSerializable(typeof(LseqPathSegment))]
[CrdtSerializable(typeof(LwwSetState))]
[CrdtSerializable(typeof(OrMapAddItem))]
[CrdtSerializable(typeof(OrMapRemoveItem))]
[CrdtSerializable(typeof(OrSetAddItem))]
[CrdtSerializable(typeof(OrSetRemoveItem))]
[CrdtSerializable(typeof(OrSetState))]
[CrdtSerializable(typeof(OriginSyncRequirement))]
[CrdtSerializable(typeof(PnCounterState))]
[CrdtSerializable(typeof(PositionalIdentifier))]
[CrdtSerializable(typeof(PositionalItem))]
[CrdtSerializable(typeof(ReplicaSyncRequirement))]
[CrdtSerializable(typeof(RgaIdentifier))]
[CrdtSerializable(typeof(RgaItem))]
[CrdtSerializable(typeof(TreeAddNodePayload))]
[CrdtSerializable(typeof(TreeMoveNodePayload))]
[CrdtSerializable(typeof(TreeNode))]
[CrdtSerializable(typeof(TreeRemoveNodePayload))]
[CrdtSerializable(typeof(TwoPhaseGraphState))]
[CrdtSerializable(typeof(TwoPhaseSetState))]
[CrdtSerializable(typeof(UnappliedOperation))]
[CrdtSerializable(typeof(VotePayload))]
[CrdtSerializable(typeof(EpochPayload))]
[CrdtSerializable(typeof(QuorumPayload))]
[CrdtSerializable(typeof(CompositePartitionKey))]
[CrdtSerializable(typeof(DataPartition))]
[CrdtSerializable(typeof(HeaderPartition))]
[CrdtSerializable(typeof(PartitionContent))]
[CrdtSerializable(typeof(SplitResult))]
[CrdtSerializable(typeof(AddEdgeIntent))]
[CrdtSerializable(typeof(AddIntent))]
[CrdtSerializable(typeof(AddNodeIntent))]
[CrdtSerializable(typeof(AddVertexIntent))]
[CrdtSerializable(typeof(ClearIntent))]
[CrdtSerializable(typeof(EpochClearIntent))]
[CrdtSerializable(typeof(IncrementIntent))]
[CrdtSerializable(typeof(InsertIntent))]
[CrdtSerializable(typeof(MapIncrementIntent))]
[CrdtSerializable(typeof(MapRemoveIntent))]
[CrdtSerializable(typeof(MapSetIntent))]
[CrdtSerializable(typeof(MoveNodeIntent))]
[CrdtSerializable(typeof(RemoveEdgeIntent))]
[CrdtSerializable(typeof(RemoveIntent))]
[CrdtSerializable(typeof(RemoveNodeIntent))]
[CrdtSerializable(typeof(RemoveValueIntent))]
[CrdtSerializable(typeof(RemoveVertexIntent))]
[CrdtSerializable(typeof(SetIndexIntent))]
[CrdtSerializable(typeof(SetIntent))]
[CrdtSerializable(typeof(VoteIntent))]
[CrdtSerializable(typeof(object))]
[CrdtSerializable(typeof(IComparable))]
[CrdtSerializable(typeof(ICrdtTimestamp))]
[CrdtSerializable(typeof(ISet<object>))]
[CrdtSerializable(typeof(HashSet<object>))]
[CrdtSerializable(typeof(ISet<Edge>))]
[CrdtSerializable(typeof(HashSet<Edge>))]
[CrdtSerializable(typeof(ISet<Guid>))]
[CrdtSerializable(typeof(ISet<CrdtOperation>))]
[CrdtSerializable(typeof(HashSet<CrdtOperation>))]
[CrdtSerializable(typeof(HashSet<long>))]
[CrdtSerializable(typeof(IReadOnlyList<CrdtOperation>))]
[CrdtSerializable(typeof(ImmutableList<LseqPathSegment>))]
[CrdtSerializable(typeof(IDictionary<string, int>))]
[CrdtSerializable(typeof(Dictionary<string, int>))]
[CrdtSerializable(typeof(IDictionary<string, long>))]
[CrdtSerializable(typeof(Dictionary<string, long>))]
[CrdtSerializable(typeof(IDictionary<string, CausalTimestamp>))]
[CrdtSerializable(typeof(Dictionary<string, CausalTimestamp>))]
[CrdtSerializable(typeof(IDictionary<string, TwoPhaseSetState>))]
[CrdtSerializable(typeof(Dictionary<string, TwoPhaseSetState>))]
[CrdtSerializable(typeof(IDictionary<string, LwwSetState>))]
[CrdtSerializable(typeof(Dictionary<string, LwwSetState>))]
[CrdtSerializable(typeof(IDictionary<string, OrSetState>))]
[CrdtSerializable(typeof(Dictionary<string, OrSetState>))]
[CrdtSerializable(typeof(IDictionary<string, TwoPhaseGraphState>))]
[CrdtSerializable(typeof(Dictionary<string, TwoPhaseGraphState>))]
[CrdtSerializable(typeof(IDictionary<string, List<PositionalIdentifier>>))]
[CrdtSerializable(typeof(Dictionary<string, List<PositionalIdentifier>>))]
[CrdtSerializable(typeof(IDictionary<string, List<LseqItem>>))]
[CrdtSerializable(typeof(Dictionary<string, List<LseqItem>>))]
[CrdtSerializable(typeof(IDictionary<string, List<RgaItem>>))]
[CrdtSerializable(typeof(Dictionary<string, List<RgaItem>>))]
[CrdtSerializable(typeof(IDictionary<string, ISet<long>>))]
[CrdtSerializable(typeof(IReadOnlyDictionary<string, OriginSyncRequirement>))]
[CrdtSerializable(typeof(IDictionary<string, IDictionary<object, ISet<string>>>))]
[CrdtSerializable(typeof(Dictionary<string, IDictionary<object, ISet<string>>>))]
[CrdtSerializable(typeof(IDictionary<string, IDictionary<string, AverageRegisterValue>>))]
[CrdtSerializable(typeof(Dictionary<string, IDictionary<string, AverageRegisterValue>>))]
[CrdtSerializable(typeof(IDictionary<string, IDictionary<object, CausalTimestamp>>))]
[CrdtSerializable(typeof(Dictionary<string, IDictionary<object, CausalTimestamp>>))]
[CrdtSerializable(typeof(IDictionary<string, IDictionary<object, PnCounterState>>))]
[CrdtSerializable(typeof(Dictionary<string, IDictionary<object, PnCounterState>>))]
[CrdtSerializable(typeof(IDictionary<object, ICrdtTimestamp>))]
[CrdtSerializable(typeof(IDictionary<object, CausalTimestamp>))]
[CrdtSerializable(typeof(IDictionary<object, ISet<Guid>>))]
[CrdtSerializable(typeof(IDictionary<object, IDictionary<Guid, CausalTimestamp>>))]
[CrdtSerializable(typeof(IDictionary<object, TreeNode>))]
[CrdtSerializable(typeof(Dictionary<object, TreeNode>))]
[CrdtSerializable(typeof(CompositePartitionKey?))]
[CrdtSerializable(typeof(RgaIdentifier?))]
internal partial class InternalCrdtContext : CrdtContext
{
}