namespace Ama.CRDT.Models.Aot;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using Ama.CRDT.Attributes;
using Ama.CRDT.Models;
using Ama.CRDT.Models.Decorators;
using Ama.CRDT.Models.Intents;
using Ama.CRDT.Models.Intents.Decorators;
using Ama.CRDT.Models.Partitioning;

/// <summary>
/// An internal AOT-generated context containing metadata for all core CRDT models.
/// This is automatically registered into the DI container by <see cref="Extensions.ServiceCollectionExtensions.AddCrdt"/>.
/// </summary>
[CrdtAotType(typeof(AverageRegisterValue))]
[CrdtAotType(typeof(BidirectionalSyncRequirements))]
[CrdtAotType(typeof(CausalTimestamp))]
[CrdtAotType(typeof(CrdtGraph))]
[CrdtAotType(typeof(CrdtMetadata))]
[CrdtAotType(typeof(CrdtOperation))]
[CrdtAotType(typeof(CrdtPatch))]
[CrdtAotType(typeof(CrdtTree))]
[CrdtAotType(typeof(DottedVersionVector))]
[CrdtAotType(typeof(Edge))]
[CrdtAotType(typeof(EpochTimestamp))]
[CrdtAotType(typeof(GraphEdgePayload))]
[CrdtAotType(typeof(GraphVertexPayload))]
[CrdtAotType(typeof(JournaledOperation))]
[CrdtAotType(typeof(LseqIdentifier))]
[CrdtAotType(typeof(LseqItem))]
[CrdtAotType(typeof(LseqPathSegment))]
[CrdtAotType(typeof(LwwSetState))]
[CrdtAotType(typeof(OrMapAddItem))]
[CrdtAotType(typeof(OrMapRemoveItem))]
[CrdtAotType(typeof(OrSetAddItem))]
[CrdtAotType(typeof(OrSetRemoveItem))]
[CrdtAotType(typeof(OrSetState))]
[CrdtAotType(typeof(OriginSyncRequirement))]
[CrdtAotType(typeof(PnCounterState))]
[CrdtAotType(typeof(PositionalIdentifier))]
[CrdtAotType(typeof(PositionalItem))]
[CrdtAotType(typeof(ReplicaSyncRequirement))]
[CrdtAotType(typeof(RgaIdentifier))]
[CrdtAotType(typeof(RgaItem))]
[CrdtAotType(typeof(TreeAddNodePayload))]
[CrdtAotType(typeof(TreeMoveNodePayload))]
[CrdtAotType(typeof(TreeNode))]
[CrdtAotType(typeof(TreeRemoveNodePayload))]
[CrdtAotType(typeof(TwoPhaseGraphState))]
[CrdtAotType(typeof(TwoPhaseSetState))]
[CrdtAotType(typeof(UnappliedOperation))]
[CrdtAotType(typeof(VotePayload))]
[CrdtAotType(typeof(EpochPayload))]
[CrdtAotType(typeof(QuorumPayload))]
[CrdtAotType(typeof(CompositePartitionKey))]
[CrdtAotType(typeof(DataPartition))]
[CrdtAotType(typeof(HeaderPartition))]
[CrdtAotType(typeof(PartitionContent))]
[CrdtAotType(typeof(SplitResult))]
[CrdtAotType(typeof(AddEdgeIntent))]
[CrdtAotType(typeof(AddIntent))]
[CrdtAotType(typeof(AddNodeIntent))]
[CrdtAotType(typeof(AddVertexIntent))]
[CrdtAotType(typeof(ClearIntent))]
[CrdtAotType(typeof(EpochClearIntent))]
[CrdtAotType(typeof(IncrementIntent))]
[CrdtAotType(typeof(InsertIntent))]
[CrdtAotType(typeof(MapIncrementIntent))]
[CrdtAotType(typeof(MapRemoveIntent))]
[CrdtAotType(typeof(MapSetIntent))]
[CrdtAotType(typeof(MoveNodeIntent))]
[CrdtAotType(typeof(RemoveEdgeIntent))]
[CrdtAotType(typeof(RemoveIntent))]
[CrdtAotType(typeof(RemoveNodeIntent))]
[CrdtAotType(typeof(RemoveValueIntent))]
[CrdtAotType(typeof(RemoveVertexIntent))]
[CrdtAotType(typeof(SetIndexIntent))]
[CrdtAotType(typeof(SetIntent))]
[CrdtAotType(typeof(VoteIntent))]
[CrdtAotType(typeof(object))]
[CrdtAotType(typeof(IComparable))]
[CrdtAotType(typeof(ICrdtTimestamp))]
[CrdtAotType(typeof(ISet<object>))]
[CrdtAotType(typeof(HashSet<object>))]
[CrdtAotType(typeof(ISet<Edge>))]
[CrdtAotType(typeof(HashSet<Edge>))]
[CrdtAotType(typeof(ISet<Guid>))]
[CrdtAotType(typeof(ISet<CrdtOperation>))]
[CrdtAotType(typeof(HashSet<CrdtOperation>))]
[CrdtAotType(typeof(HashSet<long>))]
[CrdtAotType(typeof(IReadOnlyList<CrdtOperation>))]
[CrdtAotType(typeof(ImmutableList<LseqPathSegment>))]
[CrdtAotType(typeof(IDictionary<string, ICrdtMetadataState>))]
[CrdtAotType(typeof(Dictionary<string, ICrdtMetadataState>))]
[CrdtAotType(typeof(IDictionary<string, long>))]
[CrdtAotType(typeof(Dictionary<string, long>))]
[CrdtAotType(typeof(IDictionary<string, CausalTimestamp>))]
[CrdtAotType(typeof(Dictionary<string, CausalTimestamp>))]
[CrdtAotType(typeof(IDictionary<string, TwoPhaseSetState>))]
[CrdtAotType(typeof(Dictionary<string, TwoPhaseSetState>))]
[CrdtAotType(typeof(IDictionary<string, LwwSetState>))]
[CrdtAotType(typeof(Dictionary<string, LwwSetState>))]
[CrdtAotType(typeof(IDictionary<string, OrSetState>))]
[CrdtAotType(typeof(Dictionary<string, OrSetState>))]
[CrdtAotType(typeof(IDictionary<string, TwoPhaseGraphState>))]
[CrdtAotType(typeof(Dictionary<string, TwoPhaseGraphState>))]
[CrdtAotType(typeof(IDictionary<string, List<PositionalIdentifier>>))]
[CrdtAotType(typeof(Dictionary<string, List<PositionalIdentifier>>))]
[CrdtAotType(typeof(IDictionary<string, List<LseqItem>>))]
[CrdtAotType(typeof(Dictionary<string, List<LseqItem>>))]
[CrdtAotType(typeof(IDictionary<string, List<RgaItem>>))]
[CrdtAotType(typeof(Dictionary<string, List<RgaItem>>))]
[CrdtAotType(typeof(IDictionary<string, ISet<long>>))]
[CrdtAotType(typeof(IReadOnlyDictionary<string, OriginSyncRequirement>))]
[CrdtAotType(typeof(IDictionary<string, IDictionary<object, ISet<string>>>))]
[CrdtAotType(typeof(Dictionary<string, IDictionary<object, ISet<string>>>))]
[CrdtAotType(typeof(IDictionary<string, IDictionary<string, AverageRegisterValue>>))]
[CrdtAotType(typeof(Dictionary<string, IDictionary<string, AverageRegisterValue>>))]
[CrdtAotType(typeof(IDictionary<string, IDictionary<object, CausalTimestamp>>))]
[CrdtAotType(typeof(Dictionary<string, IDictionary<object, CausalTimestamp>>))]
[CrdtAotType(typeof(IDictionary<string, IDictionary<object, PnCounterState>>))]
[CrdtAotType(typeof(Dictionary<string, IDictionary<object, PnCounterState>>))]
[CrdtAotType(typeof(IDictionary<object, ICrdtTimestamp>))]
[CrdtAotType(typeof(IDictionary<object, CausalTimestamp>))]
[CrdtAotType(typeof(IDictionary<object, ISet<Guid>>))]
[CrdtAotType(typeof(IDictionary<object, IDictionary<Guid, CausalTimestamp>>))]
[CrdtAotType(typeof(IDictionary<object, TreeNode>))]
[CrdtAotType(typeof(Dictionary<object, TreeNode>))]
[CrdtAotType(typeof(CompositePartitionKey?))]
[CrdtAotType(typeof(RgaIdentifier?))]
internal partial class InternalCrdtAotContext : CrdtAotContext
{
}