namespace Ama.CRDT.SourceGenerators;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator(LanguageNames.CSharp)]
public class CrdtContextGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Ama.CRDT.Attributes.CrdtSerializableAttribute",
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => ctx.TargetSymbol as INamedTypeSymbol)
            .Where(static m => m is not null);

        var compilationAndClasses = context.CompilationProvider.Combine(provider.Collect());

        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static void Execute(Compilation compilation, ImmutableArray<INamedTypeSymbol?> contextClasses, SourceProductionContext spc)
    {
        var distinctClasses = contextClasses
            .Where(c => c is not null)
            .Select(c => c!)
            .Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var contextClass in distinctClasses)
        {
            var attributes = contextClass.GetAttributes()
                .Where(a => a.AttributeClass?.ToDisplayString() == "Ama.CRDT.Attributes.CrdtSerializableAttribute")
                .ToList();

            var typesToGenerate = new List<ITypeSymbol>();

            foreach (var attr in attributes)
            {
                if (attr.ConstructorArguments.Length == 1 && attr.ConstructorArguments[0].Value is ITypeSymbol targetType)
                {
                    typesToGenerate.Add(targetType);
                }
            }

            if (typesToGenerate.Count > 0)
            {
                var sourceCode = GenerateContextClass(contextClass, typesToGenerate);
                spc.AddSource($"{contextClass.Name}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
            }
        }
    }

    private static string GenerateContextClass(INamedTypeSymbol contextClass, List<ITypeSymbol> types)
    {
        var sb = new StringBuilder();
        var namespaceName = contextClass.ContainingNamespace.ToDisplayString();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    partial class {contextClass.Name}");
        sb.AppendLine("    {");
        sb.AppendLine("        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::Ama.CRDT.Models.Aot.CrdtTypeInfo> _typeInfos = new()");
        sb.AppendLine("        {");

        foreach (var type in types)
        {
            var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            [typeof({typeName})] = {GenerateTypeInfo(type, typeName)},");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        public override global::Ama.CRDT.Models.Aot.CrdtTypeInfo? GetTypeInfo(global::System.Type type)");
        sb.AppendLine("        {");
        sb.AppendLine("            return _typeInfos.TryGetValue(type, out var info) ? info : null;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateTypeInfo(ITypeSymbol type, string fullyQualifiedTypeName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("new global::Ama.CRDT.Models.Aot.CrdtTypeInfo(");
        sb.AppendLine($"                type: typeof({fullyQualifiedTypeName}),");

        bool hasParameterlessCtor = type.TypeKind == TypeKind.Class && !type.IsAbstract && 
                                    type.GetMembers(".ctor").OfType<IMethodSymbol>().Any(m => m.Parameters.Length == 0);
        
        if (hasParameterlessCtor)
        {
            sb.AppendLine($"                createInstance: () => new {fullyQualifiedTypeName}(),");
        }
        else
        {
            sb.AppendLine("                createInstance: null,");
        }

        sb.AppendLine("                properties: new global::System.Collections.Generic.Dictionary<string, global::Ama.CRDT.Models.Aot.CrdtPropertyInfo>(global::System.StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("                {");

        var properties = type.GetMembers().OfType<IPropertySymbol>()
            .Where(p => !p.IsStatic && p.DeclaredAccessibility == Accessibility.Public && !p.IsIndexer);

        foreach (var prop in properties)
        {
            var propName = prop.Name;
            var jsonName = char.ToLowerInvariant(propName[0]) + propName.Substring(1); // Basic camelCase
            var propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            var getter = prop.GetMethod != null ? $"obj => (({fullyQualifiedTypeName})obj).{propName}" : "null";
            var setter = prop.SetMethod != null ? $"(obj, val) => (({fullyQualifiedTypeName})obj).{propName} = val == null ? default! : ({propType})val" : "null";

            sb.AppendLine($"                    [\"{propName}\"] = new global::Ama.CRDT.Models.Aot.CrdtPropertyInfo(");
            sb.AppendLine($"                        name: \"{propName}\",");
            sb.AppendLine($"                        jsonName: \"{jsonName}\",");
            sb.AppendLine($"                        propertyType: typeof({propType}),");
            sb.AppendLine($"                        canRead: {(prop.GetMethod != null ? "true" : "false")},");
            sb.AppendLine($"                        canWrite: {(prop.SetMethod != null ? "true" : "false")},");
            sb.AppendLine($"                        getter: {getter},");
            sb.AppendLine($"                        setter: {setter}");
            sb.AppendLine("                    ),");
        }

        sb.AppendLine("                },");

        // Collections & Dictionary logic
        var allInterfaces = type.AllInterfaces.ToList();
        if (type.TypeKind == TypeKind.Interface)
        {
            allInterfaces.Add((INamedTypeSymbol)type);
        }

        var collectionInterface = allInterfaces.FirstOrDefault(i => i.IsGenericType && i.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.ICollection<T>");
        var dictInterface = allInterfaces.FirstOrDefault(i => i.IsGenericType && i.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.IDictionary<TKey, TValue>");

        if (collectionInterface != null)
        {
            var elementType = collectionInterface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine("                isCollection: true,");
            sb.AppendLine($"                collectionElementType: typeof({elementType}),");
            sb.AppendLine($"                collectionAdd: (col, item) => ((global::System.Collections.Generic.ICollection<{elementType}>)col).Add(({elementType})item!),");
            sb.AppendLine($"                collectionRemove: (col, item) => ((global::System.Collections.Generic.ICollection<{elementType}>)col).Remove(({elementType})item!),");
            sb.AppendLine($"                collectionClear: col => ((global::System.Collections.Generic.ICollection<{elementType}>)col).Clear(),");
        }
        else
        {
            sb.AppendLine("                isCollection: false,");
            sb.AppendLine("                collectionElementType: null,");
            sb.AppendLine("                collectionAdd: null,");
            sb.AppendLine("                collectionRemove: null,");
            sb.AppendLine("                collectionClear: null,");
        }

        if (dictInterface != null)
        {
            var keyType = dictInterface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var valueType = dictInterface.TypeArguments[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine("                isDictionary: true,");
            sb.AppendLine($"                dictionaryKeyType: typeof({keyType}),");
            sb.AppendLine($"                dictionaryValueType: typeof({valueType})");
        }
        else
        {
            sb.AppendLine("                isDictionary: false,");
            sb.AppendLine("                dictionaryKeyType: null,");
            sb.AppendLine("                dictionaryValueType: null");
        }

        sb.Append("            )");
        return sb.ToString();
    }
}