namespace Ama.CRDT.SourceGenerators;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator(LanguageNames.CSharp)]
public class CrdtAotContextGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat TypeNameFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions & ~SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static readonly SymbolDisplayFormat TypeNameWithNullableFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Ama.CRDT.Attributes.CrdtAotTypeAttribute",
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => ctx.TargetSymbol as INamedTypeSymbol)
            .Where(static m => m is not null);

        var compilationAndClasses = context.CompilationProvider.Combine(provider.Collect());

        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static void Execute(Compilation compilation, ImmutableArray<INamedTypeSymbol?> contextClasses, SourceProductionContext spc)
    {
        var distinctClasses = contextClasses
            .Where(c => c is not null)
            .Select(c => c!)
            .Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var contextClass in distinctClasses)
        {
            var attributes = contextClass.GetAttributes()
                .Where(a => a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::Ama.CRDT.Attributes.CrdtAotTypeAttribute" ||
                            a.AttributeClass?.ToDisplayString() == "Ama.CRDT.Attributes.CrdtAotTypeAttribute")
                .ToList();

            var typesToGenerate = new List<ITypeSymbol>();

            foreach (var attr in attributes)
            {
                if (attr.ConstructorArguments.Length == 1 && attr.ConstructorArguments[0].Value is ITypeSymbol targetType)
                {
                    typesToGenerate.Add(targetType);
                }
            }

            if (typesToGenerate.Count > 0)
            {
                var sourceCode = GenerateContextClass(contextClass, typesToGenerate);
                spc.AddSource($"{contextClass.Name}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
            }
        }
    }

    private static string GenerateContextClass(INamedTypeSymbol contextClass, List<ITypeSymbol> types)
    {
        var sb = new StringBuilder();
        var namespaceName = contextClass.ContainingNamespace.ToDisplayString();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable RS0016, RS0041, CS8603");
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    partial class {contextClass.Name}");
        sb.AppendLine("    {");
        sb.AppendLine("        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, global::Ama.CRDT.Models.Aot.CrdtTypeInfo> _typeInfos = new()");
        sb.AppendLine("        {");

        foreach (var type in types)
        {
            var typeName = type.ToDisplayString(TypeNameFormat);
            sb.AppendLine($"            [typeof({typeName})] = {GenerateTypeInfo(type, typeName)},");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        public override global::Ama.CRDT.Models.Aot.CrdtTypeInfo? GetTypeInfo(global::System.Type type)");
        sb.AppendLine("        {");
        sb.AppendLine("            return _typeInfos.TryGetValue(type, out var info) ? info : null;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public override global::System.Collections.Generic.IEnumerable<global::Ama.CRDT.Models.Aot.CrdtTypeInfo> GetRegisteredTypes()");
        sb.AppendLine("        {");
        sb.AppendLine("            return _typeInfos.Values;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateTypeInfo(ITypeSymbol type, string fullyQualifiedTypeName)
    {
        var sb = new StringBuilder();
        var fullyQualifiedTypeNameNullable = type.ToDisplayString(TypeNameWithNullableFormat);
        sb.AppendLine("new global::Ama.CRDT.Models.Aot.CrdtTypeInfo(");
        sb.AppendLine($"                type: typeof({fullyQualifiedTypeName}),");

        string createInstanceExpr = "null";
        string createWithArgsExpr = "null";

        bool hasParameterlessCtor = type.TypeKind == TypeKind.Class && !type.IsAbstract && 
                                    type.GetMembers(".ctor").OfType<IMethodSymbol>().Any(m => m.Parameters.Length == 0);
        
        bool hasRequiredMembers = type.GetMembers().Any(m => 
            (m is IPropertySymbol prop && prop.IsRequired) || 
            (m is IFieldSymbol field && field.IsRequired));

        var constructedFrom = type is INamedTypeSymbol nts && nts.IsGenericType ? nts.ConstructedFrom.ToDisplayString() : "";

        if (type.TypeKind == TypeKind.Interface && type is INamedTypeSymbol namedInterface && namedInterface.IsGenericType)
        {
            var typeArgsNullable = string.Join(", ", namedInterface.TypeArguments.Select(t => t.ToDisplayString(TypeNameWithNullableFormat)));
            
            if (constructedFrom == "System.Collections.Generic.IEnumerable<T>" ||
                constructedFrom == "System.Collections.Generic.ICollection<T>" ||
                constructedFrom == "System.Collections.Generic.IList<T>" ||
                constructedFrom == "System.Collections.Generic.IReadOnlyCollection<T>" ||
                constructedFrom == "System.Collections.Generic.IReadOnlyList<T>")
            {
                createInstanceExpr = $"() => new global::System.Collections.Generic.List<{typeArgsNullable}>()";
            }
            else if (constructedFrom == "System.Collections.Generic.ISet<T>" ||
                     constructedFrom == "System.Collections.Generic.IReadOnlySet<T>")
            {
                createInstanceExpr = $"() => new global::System.Collections.Generic.HashSet<{typeArgsNullable}>()";
            }
            else if (constructedFrom == "System.Collections.Generic.IDictionary<TKey, TValue>" ||
                     constructedFrom == "System.Collections.Generic.IReadOnlyDictionary<TKey, TValue>")
            {
                createInstanceExpr = $"() => new global::System.Collections.Generic.Dictionary<{typeArgsNullable}>()";
            }
        }
        else if (constructedFrom == "System.Collections.Generic.KeyValuePair<TKey, TValue>")
        {
            var keyTypeNullable = ((INamedTypeSymbol)type).TypeArguments[0].ToDisplayString(TypeNameWithNullableFormat);
            var valTypeNullable = ((INamedTypeSymbol)type).TypeArguments[1].ToDisplayString(TypeNameWithNullableFormat);
            
            createWithArgsExpr = $"args => new {fullyQualifiedTypeNameNullable}(args[0] == null ? default! : ({keyTypeNullable})args[0], args[1] == null ? default! : ({valTypeNullable})args[1])";
            createInstanceExpr = $"() => default({fullyQualifiedTypeNameNullable})"; // Default struct for parameterless
        }
        else if (!hasRequiredMembers)
        {
            if (hasParameterlessCtor)
            {
                createInstanceExpr = $"() => new {fullyQualifiedTypeNameNullable}()";
            }
            else if (type.IsValueType)
            {
                createInstanceExpr = $"() => default({fullyQualifiedTypeNameNullable})";
            }
        }

        sb.AppendLine($"                createInstance: {createInstanceExpr},");
        sb.AppendLine($"                createWithArgs: {createWithArgsExpr},");

        sb.AppendLine("                properties: new global::System.Collections.Generic.Dictionary<string, global::Ama.CRDT.Models.Aot.CrdtPropertyInfo>(global::System.StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("                {");

        var properties = type.GetMembers().OfType<IPropertySymbol>()
            .Where(p => !p.IsStatic && p.DeclaredAccessibility == Accessibility.Public && !p.IsIndexer);

        foreach (var prop in properties)
        {
            var propName = prop.Name;
            var jsonName = char.ToLowerInvariant(propName[0]) + propName.Substring(1); // Basic camelCase
            
            var propType = prop.Type.ToDisplayString(TypeNameFormat);
            var propTypeNullable = prop.Type.ToDisplayString(TypeNameWithNullableFormat);

            var hasGetter = prop.GetMethod != null;
            var hasSetter = prop.SetMethod != null && !prop.SetMethod.IsInitOnly;

            var getter = hasGetter ? $"obj => (({fullyQualifiedTypeNameNullable})obj).{propName}" : "null";
            var setter = hasSetter ? $"(obj, val) => (({fullyQualifiedTypeNameNullable})obj).{propName} = val == null ? default! : ({propTypeNullable})val" : "null";

            // Extract Strategy Attributes to be compiled into AOT
            var attributes = prop.GetAttributes();
            var strategyAttr = attributes.FirstOrDefault(a => InheritsFrom(a.AttributeClass, "Ama.CRDT.Attributes.CrdtStrategyAttribute"));
            var decoratorAttrs = attributes.Where(a => InheritsFrom(a.AttributeClass, "Ama.CRDT.Attributes.CrdtStrategyDecoratorAttribute"))
                                           .OrderBy(a => a.AttributeClass?.Name, System.StringComparer.Ordinal)
                                           .ToList();

            var strategyAttributeExpr = strategyAttr != null ? GetAttributeCreationExpression(strategyAttr) : "null";
            var decoratorAttributesExpr = decoratorAttrs.Count > 0 
                ? $"new global::Ama.CRDT.Attributes.CrdtStrategyDecoratorAttribute[] {{ {string.Join(", ", decoratorAttrs.Select(a => GetAttributeCreationExpression(a)))} }}" 
                : "global::System.Array.Empty<global::Ama.CRDT.Attributes.CrdtStrategyDecoratorAttribute>()";

            sb.AppendLine($"                    [\"{propName}\"] = new global::Ama.CRDT.Models.Aot.CrdtPropertyInfo(");
            sb.AppendLine($"                        name: \"{propName}\",");
            sb.AppendLine($"                        jsonName: \"{jsonName}\",");
            sb.AppendLine($"                        propertyType: typeof({propType}),");
            sb.AppendLine($"                        canRead: {(hasGetter ? "true" : "false")},");
            sb.AppendLine($"                        canWrite: {(hasSetter ? "true" : "false")},");
            sb.AppendLine($"                        getter: {getter},");
            sb.AppendLine($"                        setter: {setter},");
            sb.AppendLine($"                        strategyAttribute: {strategyAttributeExpr},");
            sb.AppendLine($"                        decoratorAttributes: {decoratorAttributesExpr}");
            sb.AppendLine("                    ),");
        }

        sb.AppendLine("                },");

        // Collections & Dictionary logic
        var allInterfaces = type.AllInterfaces.ToList();
        if (type.TypeKind == TypeKind.Interface)
        {
            allInterfaces.Add((INamedTypeSymbol)type);
        }

        var collectionInterface = allInterfaces.FirstOrDefault(i => i.IsGenericType && (i.ConstructedFrom.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Collections.Generic.ICollection<T>" || i.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.ICollection<T>"));
        var dictInterface = allInterfaces.FirstOrDefault(i => i.IsGenericType && (i.ConstructedFrom.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Collections.Generic.IDictionary<TKey, TValue>" || i.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.IDictionary<TKey, TValue>"));

        if (collectionInterface != null)
        {
            var elementType = collectionInterface.TypeArguments[0].ToDisplayString(TypeNameFormat);
            var elementTypeNullable = collectionInterface.TypeArguments[0].ToDisplayString(TypeNameWithNullableFormat);
            
            sb.AppendLine("                isCollection: true,");
            sb.AppendLine($"                collectionElementType: typeof({elementType}),");
            sb.AppendLine($"                collectionAdd: (col, item) => ((global::System.Collections.Generic.ICollection<{elementTypeNullable}>)col).Add(({elementTypeNullable})item!),");
            sb.AppendLine($"                collectionRemove: (col, item) => ((global::System.Collections.Generic.ICollection<{elementTypeNullable}>)col).Remove(({elementTypeNullable})item!),");
            sb.AppendLine($"                collectionClear: col => ((global::System.Collections.Generic.ICollection<{elementTypeNullable}>)col).Clear(),");
        }
        else
        {
            sb.AppendLine("                isCollection: false,");
            sb.AppendLine("                collectionElementType: null,");
            sb.AppendLine("                collectionAdd: null,");
            sb.AppendLine("                collectionRemove: null,");
            sb.AppendLine("                collectionClear: null,");
        }

        if (dictInterface != null)
        {
            var keyType = dictInterface.TypeArguments[0].ToDisplayString(TypeNameFormat);
            var valueType = dictInterface.TypeArguments[1].ToDisplayString(TypeNameFormat);
            sb.AppendLine("                isDictionary: true,");
            sb.AppendLine($"                dictionaryKeyType: typeof({keyType}),");
            sb.AppendLine($"                dictionaryValueType: typeof({valueType})");
        }
        else
        {
            sb.AppendLine("                isDictionary: false,");
            sb.AppendLine("                dictionaryKeyType: null,");
            sb.AppendLine("                dictionaryValueType: null");
        }

        sb.Append("            )");
        return sb.ToString();
    }

    private static bool InheritsFrom(INamedTypeSymbol? symbol, string baseName)
    {
        while (symbol != null)
        {
            if (symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == $"global::{baseName}" || 
                symbol.ToDisplayString() == baseName) 
            {
                return true;
            }
            symbol = symbol.BaseType;
        }
        return false;
    }

    private static string GetAttributeCreationExpression(AttributeData attr)
    {
        // Intersect raw syntax tree to capture exact text when Semantic Model fails to bind arguments
        if (attr.ApplicationSyntaxReference?.GetSyntax() is AttributeSyntax attrSyntax && attrSyntax.ArgumentList != null)
        {
            var argsStr = new List<string>();
            var constructorArgsIndex = 0;

            foreach (var argSyntax in attrSyntax.ArgumentList.Arguments)
            {
                if (argSyntax.NameEquals != null) // Property assignment (e.g. QuorumSize = 2)
                {
                    var name = argSyntax.NameEquals.Name.Identifier.Text;
                    var semanticArg = attr.NamedArguments.FirstOrDefault(na => na.Key == name);
                    
                    if (semanticArg.Key != null)
                    {
                        argsStr.Add($"{name} = {FormatTypedConstant(semanticArg.Value)}");
                    }
                    else
                    {
                        // Semantic Model dropped it (likely a compilation error or incorrect test setup), copy exact syntax
                        argsStr.Add(argSyntax.ToString());
                    }
                }
                else if (argSyntax.NameColon != null) // Named constructor param (e.g. quorumSize: 2)
                {
                    argsStr.Add(argSyntax.ToString());
                    constructorArgsIndex++;
                }
                else // Positional parameter
                {
                    if (constructorArgsIndex < attr.ConstructorArguments.Length)
                    {
                        argsStr.Add(FormatTypedConstant(attr.ConstructorArguments[constructorArgsIndex]));
                    }
                    else
                    {
                        argsStr.Add(argSyntax.ToString());
                    }
                    constructorArgsIndex++;
                }
            }

            return $"new {attr.AttributeClass!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}({string.Join(", ", argsStr)})";
        }

        // Fallback for dynamically added attributes missing source syntax
        var args = new List<string>();
        foreach (var arg in attr.ConstructorArguments)
        {
            args.Add(FormatTypedConstant(arg));
        }
        
        var namedArgs = new List<string>();
        foreach (var arg in attr.NamedArguments)
        {
            namedArgs.Add($"{arg.Key} = {FormatTypedConstant(arg.Value)}");
        }
        
        var allArgs = string.Join(", ", args.Concat(namedArgs));
        return $"new {attr.AttributeClass!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}({allArgs})";
    }

    private static string FormatTypedConstant(TypedConstant constant)
    {
        if (constant.IsNull)
        {
            return "null";
        }

        if (constant.Kind == TypedConstantKind.Type && constant.Value is ITypeSymbol typeSymbol)
        {
            return $"typeof({typeSymbol.ToDisplayString(TypeNameFormat)})";
        }

        if (constant.Kind == TypedConstantKind.Enum && constant.Value != null)
        {
            return $"({constant.Type!.ToDisplayString(TypeNameFormat)}){constant.Value}";
        }

        if (constant.Kind == TypedConstantKind.Array)
        {
            var elements = constant.Values.Select(FormatTypedConstant);
            return $"new {constant.Type!.ToDisplayString(TypeNameFormat)} {{ {string.Join(", ", elements)} }}";
        }

        if (constant.Value is string strValue)
        {
            // Escape literal strings properly for generated code
            return $"\"{strValue.Replace("\"", "\\\"")}\"";
        }
        
        if (constant.Value is bool b)
        {
             return b ? "true" : "false";
        }

        return constant.Value!.ToString();
    }
}