namespace Ama.CRDT.Attributes;

using System;

/// <summary>
/// Maps an intent builder extension method to the specific explicit intent type it generates.
/// Used by Roslyn analyzers for compile-time validation without hardcoded mappings.
/// </summary>
[AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
public sealed class CrdtIntentMappingAttribute : Attribute
{
    /// <summary>
    /// Gets the type of the intent generated by the decorated method.
    /// </summary>
    public Type IntentType { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="CrdtIntentMappingAttribute"/> class.
    /// </summary>
    /// <param name="intentType">The type of the intent generated.</param>
    public CrdtIntentMappingAttribute(Type intentType)
    {
        IntentType = intentType;
    }
}