namespace Ama.CRDT.Services.Journaling;

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Ama.CRDT.Models;

/// <summary>
/// Defines a contract for an operation journal that captures explicitly generated 
/// and successfully applied CRDT operations, and provides access to retrieve them.
/// Implementing this interface allows external protocols to intercept operations 
/// in order to store them in an external datastore (e.g., event store, database, message queue) 
/// and serve them to other replicas.
/// </summary>
public interface ICrdtOperationJournal
{
    /// <summary>
    /// Synchronously appends a list of CRDT operations to the journal.
    /// This is typically called when operations are generated via synchronous intent builders.
    /// </summary>
    /// <param name="operations">The list of operations to append.</param>
    void Append(IReadOnlyList<CrdtOperation> operations);

    /// <summary>
    /// Asynchronously appends a list of CRDT operations to the journal.
    /// This is typically called when patches are applied or generated asynchronously.
    /// </summary>
    /// <param name="operations">The list of operations to append.</param>
    /// <param name="cancellationToken">A cancellation token that can be used to cancel the work.</param>
    /// <returns>A task that represents the asynchronous append operation.</returns>
    Task AppendAsync(IReadOnlyList<CrdtOperation> operations, CancellationToken cancellationToken = default);

    /// <summary>
    /// Retrieves operations generated by a specific origin replica within a contiguous range of global clock values.
    /// </summary>
    /// <param name="originReplicaId">The identifier of the origin replica.</param>
    /// <param name="minGlobalClock">The exclusive minimum global clock value (operations must have GlobalClock > minGlobalClock).</param>
    /// <param name="maxGlobalClock">The inclusive maximum global clock value (operations must have GlobalClock &lt;= maxGlobalClock).</param>
    /// <param name="cancellationToken">A cancellation token.</param>
    /// <returns>An asynchronous stream of operations.</returns>
    IAsyncEnumerable<CrdtOperation> GetOperationsByRangeAsync(string originReplicaId, long minGlobalClock, long maxGlobalClock, CancellationToken cancellationToken = default);

    /// <summary>
    /// Retrieves specific out-of-order operations (dots) generated by a specific origin replica.
    /// </summary>
    /// <param name="originReplicaId">The identifier of the origin replica.</param>
    /// <param name="globalClocks">A set of specific global clock values to retrieve.</param>
    /// <param name="cancellationToken">A cancellation token.</param>
    /// <returns>An asynchronous stream of operations.</returns>
    IAsyncEnumerable<CrdtOperation> GetOperationsByDotsAsync(string originReplicaId, IEnumerable<long> globalClocks, CancellationToken cancellationToken = default);
}