namespace Modern.CRDT.Models;

/// <summary>
/// Provides configuration options for the CRDT library.
/// </summary>
public sealed class CrdtOptions
{
    /// <summary>
    /// Gets or sets the unique identifier for the current replica/process.
    /// This is used to tag operations generated by the patcher.
    /// It defaults to a new GUID if not specified.
    /// </summary>
    public string ReplicaId { get; set; } = Guid.NewGuid().ToString();
}