name: Manual NuGet Publish

on:
  workflow_dispatch:
    inputs:
      major_version:
        description: 'Major Version'
        required: true
        default: '1'
      minor_version:
        description: 'Minor Version'
        required: true
        default: '0'
      patch_version:
        description: 'Patch Version'
        required: true
        default: '0'

env:
  PROJECT_PATH: 'Ama.CRDT/Ama.CRDT.csproj'
  PACKAGE_OUTPUT_DIRECTORY: '${{ github.workspace }}/nuget'

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for unshipped APIs
        run: |
          UNSHIPPED_API_FILE="Ama.CRDT/PublicAPI.Unshipped.txt"
          if [ -f "$UNSHIPPED_API_FILE" ] && [ -s "$UNSHIPPED_API_FILE" ]; then
            echo "Error: PublicAPI.Unshipped.txt is not empty, indicating unshipped APIs."
            echo "To publish a stable release, first 'ship' these APIs by moving them to PublicAPI.Shipped.txt and clearing PublicAPI.Unshipped.txt."
            exit 1
          fi

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set Version
        id: versioning
        run: |
          PACKAGE_VERSION="${{ inputs.major_version }}.${{ inputs.minor_version }}.${{ inputs.patch_version }}"
          ASSEMBLY_VERSION="${{ inputs.major_version }}.${{ inputs.minor_version }}.${{ inputs.patch_version }}.0"
          
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
          echo "ASSEMBLY_VERSION=${ASSEMBLY_VERSION}" >> $GITHUB_ENV

          echo "Package version: ${PACKAGE_VERSION}"
          echo "Assembly version: ${ASSEMBLY_VERSION}"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore -p:PackageVersion=${{ env.PACKAGE_VERSION }} -p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }}

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal -p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }}

      - name: Pack
        run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }} -p:PackageVersion=${{ env.PACKAGE_VERSION }} -p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }}

      - name: List created packages
        run: ls -R ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: Push to NuGet
        run: dotnet nuget push "${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate